/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.BankAccount;
import model.BankAccountHistory;

/**
 *
 * @author josephchakola
 */
public class CreateBankAccountPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateBankAccountPanel
     */
    private final BankAccountHistory bankAccountHistory;
    public CreateBankAccountPanel(BankAccountHistory bankAccountHistory) {
        initComponents();
        this.bankAccountHistory = bankAccountHistory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        daField = new javax.swing.JTextField();
        atLabel = new javax.swing.JLabel();
        phField = new javax.swing.JTextField();
        fnField = new javax.swing.JTextField();
        daLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        atField = new javax.swing.JTextField();
        mainLabel = new javax.swing.JLabel();
        caLabel = new javax.swing.JLabel();
        phLabel = new javax.swing.JLabel();
        caField = new javax.swing.JTextField();
        SaveButton = new javax.swing.JButton();

        daField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daFieldActionPerformed(evt);
            }
        });

        atLabel.setText("Account Type:");

        daLabel.setText("Debit Amount:");

        nameLabel.setText("Full Name:");

        atField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atFieldActionPerformed(evt);
            }
        });

        mainLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        mainLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainLabel.setText("Create a Bank Account");

        caLabel.setText("Credit Amount:");

        phLabel.setText("Phone Number:");

        caField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caFieldActionPerformed(evt);
            }
        });

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(atLabel)
                            .addComponent(caLabel)
                            .addComponent(daLabel)
                            .addComponent(nameLabel)
                            .addComponent(phLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SaveButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fnField)
                                    .addComponent(atField)
                                    .addComponent(daField)
                                    .addComponent(caField)
                                    .addComponent(phField, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)))))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(mainLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLabel)
                            .addComponent(fnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(atLabel)
                            .addComponent(atField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(daLabel)
                            .addComponent(daField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(caField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(phField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(phLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(54, 54, 54)
                .addComponent(SaveButton)
                .addGap(216, 216, 216))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void daFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daFieldActionPerformed

    private void atFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atFieldActionPerformed

    private void caFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caFieldActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        // TODO add your handling code here:
        BankAccount bankAccount = new BankAccount();
        if("".equals(fnField.getText())|| "".equals(atField.getText())){
            JOptionPane.showMessageDialog(this, "Complete the form.");
        } else {
            JOptionPane.showMessageDialog(this,"Bank account created");
            bankAccount.setName(fnField.getText());
            bankAccount.setAccountType(atField.getText());
            bankAccount.setCreditAmount(caField.getText());
            bankAccount.setDebitAmount(daField.getText());
            bankAccount.setPhoneNumber(phField.getText());
            bankAccountHistory.addBankAccount(bankAccount);
            fnField.setText("");
            atField.setText("");
            daField.setText("");
            caField.setText("");
            phField.setText("");
        }
        
    }//GEN-LAST:event_SaveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SaveButton;
    private javax.swing.JTextField atField;
    private javax.swing.JLabel atLabel;
    private javax.swing.JTextField caField;
    private javax.swing.JLabel caLabel;
    private javax.swing.JTextField daField;
    private javax.swing.JLabel daLabel;
    private javax.swing.JTextField fnField;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField phField;
    private javax.swing.JLabel phLabel;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
