/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userInterface;

import business.Address;
import business.Person;
import business.PersonHistory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sushmaka
 */
public class CreatePersonJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private PersonHistory personHistory;

    /**
     * Creates new form CreatePerson
     */

    public CreatePersonJPanel(JPanel userProcessContainer, PersonHistory personHistory) {
        
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.personHistory = personHistory;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        lblDateOfBirth = new javax.swing.JLabel();
        txtDateOfBirth = new javax.swing.JTextField();
        lblSocialSecurityNumber = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblLicenseNumber = new javax.swing.JLabel();
        txtSocialSecurityNumber = new javax.swing.JTextField();
        txtLicenseNumber = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lblWorkAddressStreetAddress = new javax.swing.JLabel();
        lblWorkAddressUnitNumber = new javax.swing.JLabel();
        lblWorkAddressCity = new javax.swing.JLabel();
        txtWorkAddressStreetAddress = new javax.swing.JTextField();
        txtWorkAddressUnitNumber = new javax.swing.JTextField();
        txtWorkAddressCity = new javax.swing.JTextField();
        lblWorkAddressState = new javax.swing.JLabel();
        lblWorkAddressCountry = new javax.swing.JLabel();
        lblWorkAddressZipCode = new javax.swing.JLabel();
        txtWorkAddressState = new javax.swing.JTextField();
        txtWorkAddressCountry = new javax.swing.JTextField();
        txtWorkAddressZipCode = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        lblHomeAddressStreetAddress = new javax.swing.JLabel();
        lblHomeAddressUnitNumber = new javax.swing.JLabel();
        lblHomeAddressCity = new javax.swing.JLabel();
        txtHomeAddressStreetAddress = new javax.swing.JTextField();
        txtHomeAddressUnitNumber = new javax.swing.JTextField();
        txtHomeAddressCity = new javax.swing.JTextField();
        lblHomeAddressState = new javax.swing.JLabel();
        txtHomeAddressState = new javax.swing.JTextField();
        lblHomeAddressCountry = new javax.swing.JLabel();
        lblHomeAddressZipCode = new javax.swing.JLabel();
        txtHomeAddressCountry = new javax.swing.JTextField();
        txtHomeAddressZipCode = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        txtEmail = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 204, 204));

        lblFirstName.setText("First Name");

        lblLastName.setText("Last Name");

        lblDateOfBirth.setText("Date of Birth");

        lblSocialSecurityNumber.setText("Social Security Number");

        lblEmail.setText("Email");

        lblLicenseNumber.setText("License Number");

        jLabel7.setText("Work Address");

        lblWorkAddressStreetAddress.setText("Street Address");

        lblWorkAddressUnitNumber.setText("Unit Number");

        lblWorkAddressCity.setText("City");

        lblWorkAddressState.setText("State");

        lblWorkAddressCountry.setText("Country");

        lblWorkAddressZipCode.setText("ZipCode");

        jLabel14.setText("Home Address");

        lblHomeAddressStreetAddress.setText("Street Address");

        lblHomeAddressUnitNumber.setText("Unit Number");

        lblHomeAddressCity.setText("City");

        lblHomeAddressState.setText("State");

        lblHomeAddressCountry.setText("Country");

        lblHomeAddressZipCode.setText("ZipCode");

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtHomeAddressState)
                        .addComponent(lblHomeAddressState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtHomeAddressStreetAddress)
                        .addComponent(lblHomeAddressStreetAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtWorkAddressState)
                        .addComponent(lblWorkAddressState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtWorkAddressStreetAddress)
                        .addComponent(lblWorkAddressStreetAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtFirstName)
                        .addComponent(lblSocialSecurityNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtSocialSecurityNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtLastName)
                    .addComponent(txtWorkAddressUnitNumber)
                    .addComponent(lblWorkAddressCountry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtWorkAddressCountry)
                    .addComponent(lblWorkAddressUnitNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHomeAddressUnitNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtHomeAddressUnitNumber)
                    .addComponent(lblHomeAddressCountry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtHomeAddressCountry)
                    .addComponent(txtEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtLicenseNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLicenseNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtDateOfBirth, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                        .addComponent(btnCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtHomeAddressZipCode, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblHomeAddressZipCode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtHomeAddressCity, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblHomeAddressCity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtWorkAddressZipCode, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblWorkAddressZipCode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtWorkAddressCity, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblWorkAddressCity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(92, 92, 92))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtLicenseNumber, txtSocialSecurityNumber});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtDateOfBirth, txtFirstName, txtLastName});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(lblLastName)
                    .addComponent(lblDateOfBirth))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSocialSecurityNumber)
                            .addComponent(lblEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSocialSecurityNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLicenseNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWorkAddressUnitNumber)
                    .addComponent(lblWorkAddressStreetAddress)
                    .addComponent(lblWorkAddressCity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWorkAddressStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtWorkAddressUnitNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtWorkAddressCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWorkAddressState)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblWorkAddressZipCode)
                        .addComponent(lblWorkAddressCountry)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWorkAddressState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtWorkAddressCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtWorkAddressZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(jLabel14)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHomeAddressStreetAddress)
                    .addComponent(lblHomeAddressUnitNumber)
                    .addComponent(lblHomeAddressCity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHomeAddressStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHomeAddressUnitNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHomeAddressCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHomeAddressZipCode)
                    .addComponent(lblHomeAddressState, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHomeAddressCountry))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHomeAddressZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHomeAddressState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHomeAddressCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(btnCreate)
                .addContainerGap(135, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        
        String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();
        String dateOfBirth = txtDateOfBirth.getText();
        String socialSecurityNumber = txtSocialSecurityNumber.getText();
        String email = txtEmail.getText();
        String licenseNumber = txtLicenseNumber.getText();
        String workStreetAddress = txtWorkAddressStreetAddress.getText();
        int workUnitNumber = Integer.parseInt(txtWorkAddressUnitNumber.getText());
        String workCity = txtWorkAddressCity.getText();
        String workState = txtWorkAddressState.getText();
        String workZipCode = txtWorkAddressZipCode.getText();
        String workCountry = txtWorkAddressCountry.getText();
        String homeStreetAddress = txtHomeAddressStreetAddress.getText();
        int homeUnitNumber = Integer.parseInt(txtHomeAddressUnitNumber.getText());
        String homeCity = txtHomeAddressCity.getText();
        String homeState = txtHomeAddressState.getText();
        String homeZipCode = txtHomeAddressZipCode.getText();
        String homeCountry = txtHomeAddressCountry.getText();
        
        
        Address workAddress = new Address(workStreetAddress, workUnitNumber, workCity, workState, workZipCode, workCountry);
        Address homeAddress = new Address(homeStreetAddress, homeUnitNumber, homeCity, homeState, homeZipCode, homeCountry);
        
        Person person = new Person(firstName, lastName, dateOfBirth, socialSecurityNumber, email, licenseNumber, workAddress, homeAddress);
    
        
        personHistory.addPerson(person);
        
        person.setFirstName(firstName);
        person.setLastName(lastName);
        person.setDateOfBirth(dateOfBirth);
        person.setSocialSecurityNumber(socialSecurityNumber);
        person.setEmail(email);
        person.setLicenseNumber(licenseNumber);
        person.setWorkAddress(workAddress);
        person.setHomeAddress(homeAddress);
        
        
        JOptionPane.showMessageDialog(null, "Person successfully added!");
        
        txtFirstName.setText("");
        txtLastName.setText("");
        txtDateOfBirth.setText("");
        txtSocialSecurityNumber.setText("");
        txtEmail.setText("");
        txtLicenseNumber.setText("");
        txtWorkAddressStreetAddress.setText("");
        txtWorkAddressUnitNumber.setText("");
        txtWorkAddressCity.setText("");
        txtWorkAddressState.setText("");
        txtWorkAddressZipCode.setText("");
        txtWorkAddressCountry.setText("");
        txtHomeAddressStreetAddress.setText("");
        txtHomeAddressUnitNumber.setText("");
        txtHomeAddressCity.setText("");
        txtHomeAddressState.setText("");
        txtHomeAddressZipCode.setText("");
        txtHomeAddressCountry.setText("");

    }//GEN-LAST:event_btnCreateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblDateOfBirth;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblHomeAddressCity;
    private javax.swing.JLabel lblHomeAddressCountry;
    private javax.swing.JLabel lblHomeAddressState;
    private javax.swing.JLabel lblHomeAddressStreetAddress;
    private javax.swing.JLabel lblHomeAddressUnitNumber;
    private javax.swing.JLabel lblHomeAddressZipCode;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblLicenseNumber;
    private javax.swing.JLabel lblSocialSecurityNumber;
    private javax.swing.JLabel lblWorkAddressCity;
    private javax.swing.JLabel lblWorkAddressCountry;
    private javax.swing.JLabel lblWorkAddressState;
    private javax.swing.JLabel lblWorkAddressStreetAddress;
    private javax.swing.JLabel lblWorkAddressUnitNumber;
    private javax.swing.JLabel lblWorkAddressZipCode;
    private javax.swing.JTextField txtDateOfBirth;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtHomeAddressCity;
    private javax.swing.JTextField txtHomeAddressCountry;
    private javax.swing.JTextField txtHomeAddressState;
    private javax.swing.JTextField txtHomeAddressStreetAddress;
    private javax.swing.JTextField txtHomeAddressUnitNumber;
    private javax.swing.JTextField txtHomeAddressZipCode;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtLicenseNumber;
    private javax.swing.JTextField txtSocialSecurityNumber;
    private javax.swing.JTextField txtWorkAddressCity;
    private javax.swing.JTextField txtWorkAddressCountry;
    private javax.swing.JTextField txtWorkAddressState;
    private javax.swing.JTextField txtWorkAddressStreetAddress;
    private javax.swing.JTextField txtWorkAddressUnitNumber;
    private javax.swing.JTextField txtWorkAddressZipCode;
    // End of variables declaration//GEN-END:variables
}
