/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userInterface;

import business.Person;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sushmaka
 */
public class ViewPersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPersonJPanel
     */
    
    private JPanel userProcessContainer;
    private Person person;

    public ViewPersonJPanel(JPanel userProcessContainer, Person person) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.person = person;
        populatePersonDetails();
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWorkAddressZipCode = new javax.swing.JLabel();
        txtWorkAddressState = new javax.swing.JTextField();
        txtWorkAddressCountry = new javax.swing.JTextField();
        txtWorkAddressZipCode = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        lblHomeAddressStreetAddress = new javax.swing.JLabel();
        lblHomeAddressUnitNumber = new javax.swing.JLabel();
        lblHomeAddressCity = new javax.swing.JLabel();
        txtHomeAddressStreetAddress = new javax.swing.JTextField();
        txtHomeAddressUnitNumber = new javax.swing.JTextField();
        lblLicenseNumber = new javax.swing.JLabel();
        txtHomeAddressCity = new javax.swing.JTextField();
        txtSocialSecurityNumber = new javax.swing.JTextField();
        lblHomeAddressState = new javax.swing.JLabel();
        txtLicenseNumber = new javax.swing.JTextField();
        txtHomeAddressState = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lblHomeAddressCountry = new javax.swing.JLabel();
        lblWorkAddressStreetAddress = new javax.swing.JLabel();
        lblHomeAddressZipCode = new javax.swing.JLabel();
        lblWorkAddressUnitNumber = new javax.swing.JLabel();
        txtHomeAddressCountry = new javax.swing.JTextField();
        lblWorkAddressCity = new javax.swing.JLabel();
        txtHomeAddressZipCode = new javax.swing.JTextField();
        txtWorkAddressStreetAddress = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        txtWorkAddressUnitNumber = new javax.swing.JTextField();
        txtWorkAddressCity = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        lblDateOfBirth = new javax.swing.JLabel();
        txtDateOfBirth = new javax.swing.JTextField();
        lblSocialSecurityNumber = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblWorkAddressState = new javax.swing.JLabel();
        lblWorkAddressCountry = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));

        lblWorkAddressZipCode.setText("ZipCode");

        txtWorkAddressState.setEnabled(false);

        txtWorkAddressCountry.setEnabled(false);

        txtWorkAddressZipCode.setEnabled(false);

        jLabel14.setText("Home Address");

        lblHomeAddressStreetAddress.setText("Street Address");

        lblHomeAddressUnitNumber.setText("Unit Number");

        lblHomeAddressCity.setText("City");

        txtHomeAddressStreetAddress.setEnabled(false);

        txtHomeAddressUnitNumber.setEnabled(false);

        lblLicenseNumber.setText("License Number");

        txtHomeAddressCity.setEnabled(false);

        txtSocialSecurityNumber.setEnabled(false);

        lblHomeAddressState.setText("State");

        txtLicenseNumber.setEnabled(false);

        txtHomeAddressState.setEnabled(false);

        jLabel7.setText("Work Address");

        lblHomeAddressCountry.setText("Country");

        lblWorkAddressStreetAddress.setText("Street Address");

        lblHomeAddressZipCode.setText("ZipCode");

        lblWorkAddressUnitNumber.setText("Unit Number");

        txtHomeAddressCountry.setEnabled(false);

        lblWorkAddressCity.setText("City");

        txtHomeAddressZipCode.setEnabled(false);

        txtWorkAddressStreetAddress.setEnabled(false);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        txtWorkAddressUnitNumber.setEnabled(false);

        txtWorkAddressCity.setEnabled(false);

        lblFirstName.setText("First Name");

        lblLastName.setText("Last Name");

        txtFirstName.setEnabled(false);

        txtLastName.setEnabled(false);

        lblDateOfBirth.setText("Date of Birth");

        txtDateOfBirth.setEnabled(false);

        lblSocialSecurityNumber.setText("Social Security Number");

        lblEmail.setText("Email");

        txtEmail.setEnabled(false);

        lblWorkAddressState.setText("State");

        lblWorkAddressCountry.setText("Country");

        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtHomeAddressState)
                    .addComponent(lblHomeAddressState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtHomeAddressStreetAddress)
                    .addComponent(lblHomeAddressStreetAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtWorkAddressState)
                    .addComponent(lblWorkAddressState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtWorkAddressStreetAddress)
                    .addComponent(lblWorkAddressStreetAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(txtFirstName)
                    .addComponent(lblSocialSecurityNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSocialSecurityNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(lblLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblWorkAddressUnitNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtWorkAddressUnitNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblWorkAddressCountry, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtWorkAddressCountry, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHomeAddressUnitNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtHomeAddressUnitNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHomeAddressCountry, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtHomeAddressCountry, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblDateOfBirth, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(txtDateOfBirth, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtHomeAddressZipCode, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHomeAddressZipCode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtHomeAddressCity, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHomeAddressCity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtWorkAddressZipCode, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWorkAddressZipCode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtWorkAddressCity, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWorkAddressCity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtLicenseNumber, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLicenseNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(93, 93, 93))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblDateOfBirth, lblEmail, lblFirstName, lblLastName, lblLicenseNumber, lblSocialSecurityNumber, txtDateOfBirth, txtEmail, txtFirstName, txtLicenseNumber, txtSocialSecurityNumber});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(lblLastName)
                    .addComponent(lblDateOfBirth))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSocialSecurityNumber)
                            .addComponent(lblEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSocialSecurityNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLicenseNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWorkAddressUnitNumber)
                    .addComponent(lblWorkAddressStreetAddress)
                    .addComponent(lblWorkAddressCity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWorkAddressStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtWorkAddressUnitNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtWorkAddressCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWorkAddressState)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblWorkAddressZipCode)
                        .addComponent(lblWorkAddressCountry)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWorkAddressState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtWorkAddressCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtWorkAddressZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(jLabel14)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHomeAddressStreetAddress)
                    .addComponent(lblHomeAddressUnitNumber)
                    .addComponent(lblHomeAddressCity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHomeAddressStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHomeAddressUnitNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHomeAddressCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHomeAddressZipCode)
                    .addComponent(lblHomeAddressState, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHomeAddressCountry))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHomeAddressZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHomeAddressState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHomeAddressCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate))
                .addContainerGap(145, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        txtFirstName.setEnabled(true);
        txtLastName.setEnabled(true);
        txtDateOfBirth.setEnabled(true);
        txtSocialSecurityNumber.setEnabled(true);
        txtEmail.setEnabled(true);
        txtLicenseNumber.setEnabled(true);
        txtWorkAddressStreetAddress.setEnabled(true);
        txtWorkAddressUnitNumber.setEnabled(true);
        txtWorkAddressCity.setEnabled(true);
        txtWorkAddressState.setEnabled(true);
        txtWorkAddressZipCode.setEnabled(true);
        txtWorkAddressCountry.setEnabled(true);
        txtHomeAddressStreetAddress.setEnabled(true);
        txtHomeAddressUnitNumber.setEnabled(true);
        txtHomeAddressCity.setEnabled(true);
        txtHomeAddressState.setEnabled(true);
        txtHomeAddressZipCode.setEnabled(true);
        txtHomeAddressCountry.setEnabled(true);
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        person.setFirstName(txtFirstName.getText());
        person.setLastName(txtLastName.getText());
        person.setDateOfBirth(txtDateOfBirth.getText());
        person.setSocialSecurityNumber(txtSocialSecurityNumber.getText());
        person.setEmail(txtEmail.getText());
        person.setLicenseNumber(txtLicenseNumber.getText());
    
    // Set work address details
        person.getWorkAddress().setStreetAddress(txtWorkAddressStreetAddress.getText());
        person.getWorkAddress().setUnitNumber(Integer.parseInt(txtWorkAddressUnitNumber.getText()));
        person.getWorkAddress().setCity(txtWorkAddressCity.getText());
        person.getWorkAddress().setState(txtWorkAddressState.getText());
        person.getWorkAddress().setZipCode(txtWorkAddressZipCode.getText());
        person.getWorkAddress().setCountry(txtWorkAddressCountry.getText());
    
    // Set home address details
        person.getHomeAddress().setStreetAddress(txtHomeAddressStreetAddress.getText());
        person.getHomeAddress().setUnitNumber(Integer.parseInt(txtHomeAddressUnitNumber.getText()));
        person.getHomeAddress().setCity(txtHomeAddressCity.getText());
        person.getHomeAddress().setState(txtHomeAddressState.getText());
        person.getHomeAddress().setZipCode(txtHomeAddressZipCode.getText());
        person.getHomeAddress().setCountry(txtHomeAddressCountry.getText());
        
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
        
        JOptionPane.showMessageDialog(null, "Account updated successfully!");
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblDateOfBirth;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblHomeAddressCity;
    private javax.swing.JLabel lblHomeAddressCountry;
    private javax.swing.JLabel lblHomeAddressState;
    private javax.swing.JLabel lblHomeAddressStreetAddress;
    private javax.swing.JLabel lblHomeAddressUnitNumber;
    private javax.swing.JLabel lblHomeAddressZipCode;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblLicenseNumber;
    private javax.swing.JLabel lblSocialSecurityNumber;
    private javax.swing.JLabel lblWorkAddressCity;
    private javax.swing.JLabel lblWorkAddressCountry;
    private javax.swing.JLabel lblWorkAddressState;
    private javax.swing.JLabel lblWorkAddressStreetAddress;
    private javax.swing.JLabel lblWorkAddressUnitNumber;
    private javax.swing.JLabel lblWorkAddressZipCode;
    private javax.swing.JTextField txtDateOfBirth;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtHomeAddressCity;
    private javax.swing.JTextField txtHomeAddressCountry;
    private javax.swing.JTextField txtHomeAddressState;
    private javax.swing.JTextField txtHomeAddressStreetAddress;
    private javax.swing.JTextField txtHomeAddressUnitNumber;
    private javax.swing.JTextField txtHomeAddressZipCode;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtLicenseNumber;
    private javax.swing.JTextField txtSocialSecurityNumber;
    private javax.swing.JTextField txtWorkAddressCity;
    private javax.swing.JTextField txtWorkAddressCountry;
    private javax.swing.JTextField txtWorkAddressState;
    private javax.swing.JTextField txtWorkAddressStreetAddress;
    private javax.swing.JTextField txtWorkAddressUnitNumber;
    private javax.swing.JTextField txtWorkAddressZipCode;
    // End of variables declaration//GEN-END:variables

    private void populatePersonDetails() {
        txtFirstName.setText(person.getFirstName());
        txtLastName.setText(person.getLastName());
        txtDateOfBirth.setText(person.getDateOfBirth());
        txtSocialSecurityNumber.setText(person.getSocialSecurityNumber());
        txtEmail.setText(person.getEmail());
        txtLicenseNumber.setText(person.getLicenseNumber());
        txtWorkAddressStreetAddress.setText(person.getWorkAddress().getStreetAddress());
        txtWorkAddressUnitNumber.setText(String.valueOf(person.getWorkAddress().getUnitNumber()));
        txtWorkAddressCity.setText(person.getWorkAddress().getCity());
        txtWorkAddressState.setText(person.getWorkAddress().getState());
        txtWorkAddressZipCode.setText(person.getWorkAddress().getZipCode());
        txtWorkAddressCountry.setText(person.getWorkAddress().getCountry());
        txtHomeAddressStreetAddress.setText(person.getHomeAddress().getStreetAddress());
        txtHomeAddressUnitNumber.setText(String.valueOf(person.getHomeAddress().getUnitNumber()));
        txtHomeAddressCity.setText(person.getHomeAddress().getCity());
        txtHomeAddressState.setText(person.getHomeAddress().getState());
        txtHomeAddressZipCode.setText(person.getHomeAddress().getZipCode());
        txtHomeAddressCountry.setText(person.getHomeAddress().getCountry());
    }
}
